rosrun virtual_maize_field generate_world.py \
--row_length 7 \
--rows_left 0 \
--rows_right 11 \
--rows_curve_budget 0.78539816339 \
--row_segments straight,curved \
--row_segment_curved_radius_min 4.0 \
--row_segment_curved_radius_max 5.0 \
--hole_prob 0.04 \
--hole_size_max 7 \
--ground_resolution 0.08 \
--ground_elevation_max 0.2
